install:
	install -D -m 0755 status-ctl.sh $$(pwd)/debian/status-ctl/usr/bin/status-ctl
	install -D appsettings.production.yml $$(pwd)/debian/status-ctl/etc/status-site/appsettings.yml
	install -D docker-compose.yml $$(pwd)/debian/status-ctl/etc/status-site/docker-compose.yml
