.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH ...
.
.\" Manpage for sandpiper.
.\" Contact steve.hoover@rweda.com to correct errors or typos.
.TH man 1 "15 March 2017" "0.1" "sandpiper man page"
.SH NAME
.B sandpiper 
\- compiler for TL-Verilog
.SH SYNOPSIS
.B sandpiper 
[ \fIOPTIONS\fR ]
\fB\-\i\fR \fIINFILE\fR
\fB\-o\fR \fIOUTFILE\fR
.SH DESCRIPTION
The \fBSandPiper\fR \*(Tm tool from Redwood EDA processes Transaction-Level Verilog (TL-Verilog) constructs into Verilog or SystemVerilog. TL-Verilog supports high-level constructs including pipelines and transactions which provide context for design details. From TL-Verilog designs, SandPiper generates: staging elements (such as flip-flops), signal declarations, clock gating logic, X-injection logic, etc., avoiding human error in these tedious aspects of design. Several options are available to customize the style of the generated Verilog. In addition to source code processing, SandPiper can produce logic diagrams and formatted code. This \fBsandpiper\fR executable provides the option of invoking the M4 macro preprocessor prior to running SandPiper. SandPiper can be utilized online at
.URL "http://makerchip.com" "Makerchip" .
.SH OPTIONS
For a list of command-line options, run
.PP
.nf
.RS
sandpiper -h
.RE
.fi
.PP
.SH EXAMPLES
The following command (Steve, what does it do?):
.PP
.nf
.RS
sandpiper -i ~/source.tlv -o /tmp/output.sv
.RE
.fi
.PP
.SH BUGS
Bug tracking can be found at 
.URL "http://gitlab.com/rweda/support/" "RedwoodEDA issue tracker" .
.SH COPYRIGHT
(C) Redwood EDA 2017. The terms of the license can be found at .../license.md. More information about your organization's license is reported by SandPiper.
.SH "SEE ALSO"
.URL "http://tl-x.org" "Tl-X" .
